### ISSUE TITLE
Error accessing Comic Vine

### ISSUE THREAD

**Issue by admjim** [cbanack/comic-vine-scraper#484]
Unable to scrape using Comic Vine scrapper for the last 12-24 hours.  Last worked on Nov 1 around 7:30pm CT.
Using Version 1.0.100
Getting error message starting at 7:30 am Nov 2nd. 

"The Comic Vine online database could not be reached. This may be due to temporary technical error with the database, or there may be a problem with your internet connection."

This seems to be the same issue as last time where Comic Vine made a change to their API code.  I have rebooted my system and tried again several times before posting this and have tried updating multiple files.  I have access to the internet and Comic Vine.

I posted on Reddit also to see if others are having the same issue.

**Comment by nosoop4u** [comment]
Getting the same.  Status page at https://comicvine.gamespot.com/api/ shows "You have no current rate limits...," so it's not that I in particular am being usage throttled.  Also no posts about new API features/changes at https://comicvine.gamespot.com/forums/api-developers-2334/.

I don't believe there's any logs or debug settings in the scraper, so if you're not a coder that can troubleshoot the actual code, and ComicVine truly changed something in the API that borked the scraper, we're out of luck until the developer or someone else can troubleshoot the underlying code.

**Comment by SenorSmartyPants** [comment]
```
trying to match this book automatically...
ERROR OCCURRED CONTACTING COMICVINE. RETRYING...
------------------- PYTHON ERROR ------------------------
Caught DatabaseConnectionError: Comic Vine database could not be reached
url: http://comicvine.gamespot.com/api/search/?api_key=...&client=cvscraper&format=xml&limit=100&resources=volume&field_list=name,start_year,publisher,id,image,count_of_issues&query=firefly%20-%20river%20run
CAUSE: System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
Traceback (most recent call last):
  File "C:\Users\FakeUser\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\scrapeengine.py", line 142, in scrape
  File "C:\Users\FakeUser\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\scrapeengine.py", line 257, in _ScrapeEngine__scrape
  File "C:\Users\FakeUser\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\scrapeengine.py", line 426, in _ScrapeEngine__scrape_book
  File "C:\Users\FakeUser\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\automatcher.py", line 38, in find_series_ref
  File "C:\Users\FakeUser\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\automatcher.py", line 75, in __find_best_series
  File "C:\Users\FakeUser\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\db.py", line 156, in query_series_refs
  File "C:\Users\FakeUser\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\cvdb.py", line 142, in _query_series_refs
  File "C:\Users\FakeUser\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\cvdb.py", line 165, in __query_series_refs
  File "C:\Users\FakeUser\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\cvconnection.py", line 65, in _query_series_ids_dom
  File "C:\Users\FakeUser\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\cvconnection.py", line 217, in __get_dom
  File "C:\Users\FakeUser\AppData\Roaming\cYo\ComicRack\Scripts\Comic Vine Scraper\cvconnection.py", line 174, in __get_dom
```

**Comment by nosoop4u** [comment]
Hey, so I pasted that query into my browser, replaced the "..." with my API key and I got a valid XML response, and not a 403 forbidden error.  But still getting the error when running any query thru the scraper. Not quite sure what's going on.

Where did you see that log message, SenorSmartyPants?

> url: http://comicvine.gamespot.com/api/search/?api_key=...&client=cvscraper&format=xml&limit=100&resources=volume&field_list=name,start_year,publisher,id,image,count_of_issues&query=firefly%20-%20river%20run

**Comment by SenorSmartyPants** [comment]
You have to enable the console with a command line option. I forget the code at the moment.

**Comment by WillPresley** [comment]
I wonder if CV is banning or rate-limiting the scraper user-agent? Is there still a way to set that manually in Advanced Settings? It has been a _long_ time since I've messed with any of this, but I'm having the same issue today.

**Comment by cbanack** [comment]
You can also press, Ctrl+Shift+L to get a copy of the current log (scraper window must have keyboard focus when you do this.)

**Comment by christophershad** [comment]
Tried the rate-limit fix of SCRAPE_DELAY=8 (and other numbers, up to 20) in advanced, no dice, same error 403 forbidden in the logs.

**Comment by christophershad** [comment]
Cross-posted this to the ComicVine API developer forum

**Comment by gmickd** [comment]
I found a fix to this on a Reddit [post](https://www.reddit.com/r/comicrackusers/comments/qlgfce/cv_scraper_issue/).

if you uncomment line 378 and 379 of utils.py it should work again.

```
# request.UserAgent = "[ComicVineScraper, version " + \
#   Resources.SCRIPT_VERSION + "]"
```
credit to /u/Bloodwah.

**Comment by cbanack** [comment]
Seems like Comic Vine has changed their minds ([again](https://github.com/cbanack/comic-vine-scraper/issues/483)) about which User-Agent they will accept.

I'll do my best to get a new version 1.0.101 out with the fix that you guys have so helpfully found.   Sometime soon, unless life interferes -- until then, the fix that gmickd reported will work, or you can just downgrade to version [1.0.99](http://bit.ly/cvs1099) for now.

**Comment by cbanack** [comment]
This issue should be fixed in ComicVineScraper v1.0.101, which you can get [here](https://bit.ly/cvs10101) (or from the regular download page.)

Cheers!

**Comment by rainerc** [comment]
still the same error with 1.0.1
<img width="437" alt="Screenshot 2021-11-04 at 09 34 42" src="https://user-images.githubusercontent.com/6169146/140282577-37c3fd83-11e9-4473-ac08-1869a469843e.png">
01

**Comment by Sokpan** [comment]
Seems the whole Comic Vine site is down.  Was able to access site to check my API, but now the site is not working.

**Comment by rainerc** [comment]
thanks! Should have tried that myself ;)

**Comment by cbanack** [comment]
It's working again now, right?  The ComicVine API seems to be up again...

**Comment by PaladinNikael** [comment]
> It's working again now, right? The ComicVine API seems to be up again...

Confirmed working on my end. You rock, sir!

**Comment by rainerc** [comment]
confirmed! Thanks for your great support, Cory!

**Comment by FrancisKunz** [comment]
Thx for dat amazing support

**Comment by MultiVelda** [comment]
Hey, i don't know if somebody is gonna read that but ComicVine has a huge bug where you're unable to search anything in the Forum search


![Screenshot 2024-08-17 201204](https://github.com/user-attachments/assets/5ec58d47-35e0-4316-830d-4c186296e1e8)

I'm not the only one who's having this issue.  And apparently, that error has been going on for over a year. No solution has been found

**Comment by cbanack** [comment]
@MultiVelda: Unfortunately this GitHub site is for the Comic Vine Scraper, a software tool that I wrote that can access data from the Comic Vine website...I am not involved with the Comic Vine website in any way beyond that, so I can't help with their forum bug.

The only place I can suggest that you bring this bug up is, ironically, on the ComicVine forum itself.  :/
